model:
  d_model: 256
  enc_layers: 4
  dec_layers: 2
  n_heads: 4
  ffn_dim: 512
  max_len: 256
  vocab_size_src: 16000
  vocab_size_tgt: 16000
  mlp_type: "standard" # standard or gated
  activation: "gelu" # gelu or silu
  norm_type: "layernorm" # layernorm or rmsnorm
  ff_bias: true  
  tie_decoder_embeddings: false
  layernorm_eps: 1.0e-5
  dropout: 0.05

data:
  src_lang: "fa"
  tgt_lang: "en"
  src_dev_path: "data/dev.fa"
  tgt_dev_path: "data/dev.en"
  max_tokens_per_batch: 20000
  buffer_size: 100000
  num_workers: 4
  src_spm_nbest_size: -1
  src_spm_alpha: 0.5
  tgt_spm_nbest_size: 1
  tgt_spm_alpha: 1.0
  corpora:
    - src_file: "data/train.fa"
      tgt_file: "data/train.en"
      weight: 3
      start_step: 1000
    - src_file: "../../mt/data/newscrawl.backtrans.fa-en.cleaned.filtered.fa"
      tgt_file: "../../mt/data/newscrawl.backtrans.fa-en.cleaned.filtered.en"
      weight: 3
      start_step: 0
    - src_file: "../../mt/data/madlad.backtrans.fa-en.cleaned.filtered.fa"
      tgt_file: "../../mt/data/madlad.backtrans.fa-en.cleaned.filtered.en"
      weight: 2
      start_step: 0

train:
  experiment_name: "faen-tiny"
  aim_repo: "~/mt/.aim"
  lr: 2.5e-3
  accum_steps: 6
  warmup_steps: 5000
  max_steps: 20000
  eval_steps: 1000
  max_checkpoints: 10
  precision: "bfloat16"
  grad_clip: 0.5

export:
  k: 3