model:
  d_model: 256
  enc_layers: 4
  dec_layers: 2
  n_heads: 4
  ffn_dim: 1024
  max_len: 256
  vocab_size_src: 10000
  vocab_size_tgt: 10000
  mlp_type: "gated"
  activation: "gelu" # gelu or silu
  ff_bias: false
  norm_type: "rmsnorm" # layernorm or rmsnorm
  tie_decoder_embeddings: false
  dropout: 0.05

data:
  src_lang: "fa"
  tgt_lang: "en"
  src_dev_path: "data/dev.fa"
  tgt_dev_path: "data/dev.en"
  max_tokens_per_batch: 20000
  buffer_size: 100000
  num_workers: 4
  src_spm_nbest_size: 1
  src_spm_alpha: 1.0
  tgt_spm_nbest_size: 20
  tgt_spm_alpha: 0.5
  corpora:
    - src_file: "data/train.fa"
      tgt_file: "data/train.en"
      weight: 3
      start_step: 0
    - src_file: "/home/mark/mt/data/newscrawl.backtrans.fa-en.cleaned.filtered.fa"
      tgt_file: "/home/mark/mt/data/newscrawl.backtrans.fa-en.cleaned.filtered.en"
      weight: 1
      start_step: 0
      #stop_step: 35000
    - src_file: "/home/mark/mt/data/madlad.backtrans.fa-en.cleaned.filtered.fa"
      tgt_file: "/home/mark/mt/data/madlad.backtrans.fa-en.cleaned.filtered.en"
      weight: 1
      start_step: 0
      #stop_step: 35000

train:
  experiment_name: "faen-tiny"
  aim_repo: "~/mt/.aim"
  lr: 2.5e-3
  accum_steps: 6
  warmup_steps: 5000
  max_steps: 10000
  eval_steps: 1000
  max_checkpoints: 1
  precision: "bf16"
  grad_clip: 0.2

export:
  k: 1
  export_int8: false
  quantization: "int8"