
train:
  experiment_name: "isen-tiny-1"
  lr: 1.5e-3
  accum_steps: 3
  warmup_steps: 5000
  max_steps: 40000
  eval_steps: 1000
  max_checkpoints: 10
  precision: "bfloat16" # or float16 with an older GPU
  enable_torch_compile: true 
  checkpoint_strategy: best
  early_stopping_patience: 0
  early_stopping_metric: loss

data:
  src_lang: "is"
  tgt_lang: "en"
  src_dev_path: "quickmt-valid.is-en.is"
  tgt_dev_path: "quickmt-valid.is-en.en"
  input_sentence_size: 2000000 # increase for better (but slower) tokenizer training 
  max_tokens_per_batch: 20000 # tune this value for your GPU memory
  corpora: 
    - src_file: "quickmt-train.is-en.is"
      tgt_file: "quickmt-train.is-en.en"
      weight: 2
      start_step: 5000 # delay starting due to being more difficult for the model to learn
    - src_file: "finetranslations-sample-is-en.is"
      tgt_file: "finetranslations-sample-is-en.en"
      weight: 1 # lower weight because it is synthetic data
      start_step: 0 # start at the beginning; synthetic data is easier for the model to learn
      stop_step: 30000 # finish early; synthetic data unhelpful near the end
    - src_file: "newscrawl2024-en-backtranslated-is.is"
      tgt_file: "newscrawl2024-en-backtranslated-is.en"
      weight: 1 # lower weight because it is synthetic data
      start_step: 2500 # start nearthe beginning; synthetic data is easier for the model to learn
      stop_step: 35000 # finish early; synthetic data unhelpful near the end

model:
  d_model: 384
  enc_layers: 6
  dec_layers: 2
  n_heads: 8
  n_kv_heads: 2
  ffn_dim: 1536
  max_len: 256
  vocab_size_src: 10000
  vocab_size_tgt: 10000
  ff_bias: true
  norm_type: "rmsnorm"
  mlp_type: "gated"
