# z loss instead of logit soft cap
train:
  experiment_name: "isen-tiny-test30"
  lr: 2.5e-3
  accum_steps: 8
  warmup_steps: 5000
  max_steps: 30000
  eval_steps: 1000
  max_checkpoints: 5
  precision: "bfloat16" # or float16 with an older GPU
  enable_torch_compile: true 
  checkpoint_strategy: recent
  early_stopping_patience: 0
  use_ema: false
  z_loss_coeff: 0.001
  weight_decay_embeddings: false
  scheduler_type: "cosine"
  decay_dropout: true
  dropout_decay_resolution: 0.01
  
data:
  src_lang: "is"
  tgt_lang: "en"
  src_dev_path: "data/quickmt-valid.is-en.is"
  tgt_dev_path: "data/quickmt-valid.is-en.en"
  input_sentence_size: 2000000 # increase for better (but slower) tokenizer training 
  max_tokens_per_batch: 10000 # tune this value for your GPU memory
  buffer_size: 40000
  num_workers:  4
  prefetch_factor: 128
  pad_multiple: 8
  corpora: 
    - src_file: "data/quickmt-train.is-en.is"
      tgt_file: "data/quickmt-train.is-en.en"
      weight: 3
      start_step: 8000 # delay starting due to being more difficult for the model to learn
    - src_file: "data/finetranslations.isl_Latn-eng_Latn.isl_Latn"
      tgt_file: "data/finetranslations.isl_Latn-eng_Latn.eng_Latn"
      weight: 3
      start_step: 0 # start at the beginning; synthetic data is easier for the model to learn
    - src_file: "data/newscrawl2024-en-backtranslated-is.is"
      tgt_file: "data/newscrawl2024-en-backtranslated-is.en"
      weight: 5
      start_step: 0
  pipeline:
    - path: "quickmt_train.processors.LengthFilterProcessor"
      start_step: 0 # Filter out long segments in first 10k steps - they are harder to learn from
      stop_step: 10000
      kwargs:
        min_char_length: 3
        max_char_length: 100
        length_ratio: 2.0
    - path: "quickmt_train.processors.CharacterNoiseProcessor"
      start_step: 10000 # Add a small amount of synthetic noise to hopefully make the model more robust
      kwargs:
        deletion_prob: 0.005
        swap_prob: 0.005
        repeat_prob: 0.005
        flipcase_prob: 0.005

model:
  d_model: 384
  enc_layers: 8
  dec_layers: 2
  n_heads: 4
  ffn_dim: 1536
  max_len: 256
  vocab_size_src: 10000
  vocab_size_tgt: 10000
  ff_bias: true
  norm_type: "rmsnorm"
  mlp_type: "gated"
  activation: "silu"
  dropout: 0.1
  use_rope: true

export:
  k: 5
  max_len: 256
