
train:
  experiment_name: "isen-tiny-6"
  lr: 2.0e-3
  accum_steps: 3
  warmup_steps: 5000
  max_steps: 40000
  eval_steps: 1000
  max_checkpoints: 10
  precision: "bfloat16" # or float16 with an older GPU
  enable_torch_compile: true 

data:
  src_lang: "is"
  tgt_lang: "en"
  src_dev_path: "quickmt-valid.is-en.is"
  tgt_dev_path: "quickmt-valid.is-en.en"
  input_sentence_size: 2000000 # increase for better (but slower) tokenizer training 
  max_tokens_per_batch: 20000 # tune this value for your GPU memory
  corpora: 
    - src_file: "quickmt-train.is-en.is"
      tgt_file: "quickmt-train.is-en.en"

model:
  d_model: 384
  enc_layers: 6
  dec_layers: 2
  n_heads: 4
  ffn_dim: 1536
  max_len: 256
  vocab_size_src: 10000
  vocab_size_tgt: 10000
  ff_bias: true
  norm_type: str = "rmsnorm"
  mlp_type: "gated"
